IRLib: src/backend/stemming/porter/stem.c File Reference
src/backend/stemming/porter/stem.c File Reference
#include <stdlib.h>
#include <string.h>
#include "stem.h"
#include <stdio.h>
#include <ctype.h>
Classes
struct stemmer
Defines
#define TRUE 1
#define FALSE 0
#define INC 50 /* size units in which s is increased */
#define LETTER(ch) (isupper(ch) || islower(ch))
Functions
struct stemmer * create_stemmer (void)
void free_stemmer (struct stemmer *z)
static int cons (struct stemmer *z, int i)
static int m (struct stemmer *z)
static int vowelinstem (struct stemmer *z)
static int doublec (struct stemmer *z, int j)
static int cvc (struct stemmer *z, int i)
static int ends (struct stemmer *z, char *s)
static void setto (struct stemmer *z, char *s)
static void r (struct stemmer *z, char *s)
static void step1ab (struct stemmer *z)
static void step1c (struct stemmer *z)
static void step2 (struct stemmer *z)
static void step3 (struct stemmer *z)
static void step4 (struct stemmer *z)
static void step5 (struct stemmer *z)
int stem (struct stemmer *z, char *b, int k)
void stemfile (struct stemmer *z, FILE *f)
Variables
static char * s
static int i_max = INC
Define Documentation
#define FALSE 0
Definition at line 43 of file stem.c.
Referenced by cons(), cvc(), doublec(), ends(), and vowelinstem().
#define INC 50 /* size units in which s is increased */
Definition at line 385 of file stem.c.
Referenced by stemfile(), and stemRawText().
#define LETTER (ch) (isupper(ch) || islower(ch))
Definition at line 388 of file stem.c.
Referenced by stemfile().
#define TRUE 1
Definition at line 42 of file stem.c.
Referenced by cons(), cvc(), ends(), m(), stemfile(), and vowelinstem().
Function Documentation
static int cons (struct stemmer * z, int i) [static]
Definition at line 91 of file stem.c.
References stemmer::b, FALSE, and TRUE.
Referenced by cvc(), doublec(), m(), and vowelinstem().
struct stemmer* create_stemmer (void) [read]
Definition at line 75 of file stem.c.
Referenced by stemRawText().
static int cvc (struct stemmer * z, int i) [static]
Definition at line 164 of file stem.c.
References stemmer::b, cons(), FALSE, and TRUE.
Referenced by step1ab(), and step5().
static int doublec (struct stemmer * z, int j) [static]
Definition at line 147 of file stem.c.
References stemmer::b, cons(), and FALSE.
Referenced by step1ab(), and step5().
static int ends (struct stemmer * z, char * s) [static]
Definition at line 174 of file stem.c.
References stemmer::b, FALSE, stemmer::j, stemmer::k, and TRUE.
Referenced by step1ab(), step1c(), step2(), step3(), and step4().
void free_stemmer (struct stemmer * z)
Definition at line 81 of file stem.c.
static int m (struct stemmer * z) [static]
Definition at line 110 of file stem.c.
References cons(), stemmer::j, and TRUE.
Referenced by columnsInIndex(), parseHhMmSs(), r(), sqlite3Utf16to8(), sqlite3VdbeIdxKeyCompare(), sqlite3VdbeIdxRowid(), sqlite3WhereBegin(), step1ab(), step4(), and step5().
static void r (struct stemmer * z, char * s) [static]
Definition at line 197 of file stem.c.
References m(), and setto().
Referenced by balance_nonroot(), codeOneLoopStart(), doubleToInt64(), xpath_ast_node::eval_number(), nocaseCollatingFunc(), parseDateOrTime(), parseModifier(), randomFunc(), roundFunc(), sqlite3MulInt64(), sqlite3Utf8CharLen(), sqlite3VdbeExec(), step2(), and step3().
static void setto (struct stemmer * z, char * s) [static]
Definition at line 188 of file stem.c.
References stemmer::b, stemmer::j, and stemmer::k.
Referenced by r(), and step1ab().
int stem (struct stemmer * z, char * b, int k)
Definition at line 363 of file stem.c.
References stemmer::b, stemmer::k, step1ab(), step1c(), step2(), step3(), step4(), and step5().
Referenced by stemfile(), and stemRawText().
void stemfile (struct stemmer * z, FILE * f)
Definition at line 390 of file stem.c.
References i_max, INC, LETTER, s, stem(), and TRUE.
static void step1ab (struct stemmer * z) [static]
Definition at line 221 of file stem.c.
References stemmer::b, cvc(), doublec(), ends(), stemmer::j, stemmer::k, m(), setto(), and vowelinstem().
Referenced by stem().
static void step1c (struct stemmer * z) [static]
Definition at line 247 of file stem.c.
References stemmer::b, ends(), stemmer::k, and vowelinstem().
Referenced by stem().
static void step2 (struct stemmer * z) [static]
Definition at line 257 of file stem.c.
References stemmer::b, ends(), stemmer::k, and r().
Referenced by stem().
static void step3 (struct stemmer * z) [static]
Definition at line 298 of file stem.c.
References stemmer::b, ends(), stemmer::k, and r().
Referenced by stem().
static void step4 (struct stemmer * z) [static]
Definition at line 315 of file stem.c.
References stemmer::b, ends(), stemmer::j, stemmer::k, and m().
Referenced by stem().
static void step5 (struct stemmer * z) [static]
Definition at line 345 of file stem.c.
References stemmer::b, cvc(), doublec(), stemmer::j, stemmer::k, and m().
Referenced by stem().
static int vowelinstem (struct stemmer * z) [static]
Definition at line 138 of file stem.c.
References cons(), FALSE, stemmer::j, and TRUE.
Referenced by step1ab(), and step1c().
Variable Documentation
int i_max = INC [static]
Definition at line 386 of file stem.c.
Referenced by stemfile(), and stemRawText().
char* s [static]
Definition at line 383 of file stem.c.
Referenced by computeHMS(), convert_number_to_string(), xpath_ast_node::eval_node_set(), xpath_ast_node::eval_string(), gap::flush(), localtimeOffset(), strconv_pcdata_impl< opt_eol, opt_escape >::parse(), xml_parser::parse(), xml_parser::parse_doctype_group(), xml_parser::parse_doctype_ignore(), xml_parser::parse_doctype_primitive(), strconv_attribute_impl< opt_escape >::parse_eol(), xml_parser::parse_exclamation(), xml_parser::parse_question(), strconv_attribute_impl< opt_escape >::parse_simple(), strconv_attribute_impl< opt_escape >::parse_wconv(), strconv_attribute_impl< opt_escape >::parse_wnorm(), parseHhMmSs(), gap::push(), sqlite3AtoF(), sqlite3GetVarint(), stemfile(), stemRawText(), xpath_ast_node::step_do(), strconv_cdata(), strconv_comment(), strftimeFunc(), text_output_cdata(), and text_output_escaped().