IRLib: sqlite3_module Struct Reference
sqlite3_module Struct Reference
#include <sqlite3.h>
Public Attributes
int iVersion
int(* xCreate)(sqlite3 *, void *pAux, int argc, const char *const *argv, sqlite3_vtab **ppVTab, char **)
int(* xConnect)(sqlite3 *, void *pAux, int argc, const char *const *argv, sqlite3_vtab **ppVTab, char **)
int(* xBestIndex)(sqlite3_vtab *pVTab, sqlite3_index_info *)
int(* xDisconnect)(sqlite3_vtab *pVTab)
int(* xDestroy)(sqlite3_vtab *pVTab)
int(* xOpen)(sqlite3_vtab *pVTab, sqlite3_vtab_cursor **ppCursor)
int(* xClose)(sqlite3_vtab_cursor *)
int(* xFilter)(sqlite3_vtab_cursor *, int idxNum, const char *idxStr, int argc, sqlite3_value **argv)
int(* xNext)(sqlite3_vtab_cursor *)
int(* xEof)(sqlite3_vtab_cursor *)
int(* xColumn)(sqlite3_vtab_cursor *, sqlite3_context *, int)
int(* xRowid)(sqlite3_vtab_cursor *, sqlite3_int64 *pRowid)
int(* xUpdate)(sqlite3_vtab *, int, sqlite3_value **, sqlite3_int64 *)
int(* xBegin)(sqlite3_vtab *pVTab)
int(* xSync)(sqlite3_vtab *pVTab)
int(* xCommit)(sqlite3_vtab *pVTab)
int(* xRollback)(sqlite3_vtab *pVTab)
int(* xFindFunction)(sqlite3_vtab *pVtab, int nArg, const char *zName, void(**pxFunc)(sqlite3_context *, int, sqlite3_value **), void **ppArg)
int(* xRename)(sqlite3_vtab *pVtab, const char *zNew)
int(* xSavepoint)(sqlite3_vtab *pVTab, int)
int(* xRelease)(sqlite3_vtab *pVTab, int)
int(* xRollbackTo)(sqlite3_vtab *pVTab, int)
Detailed Description
Definition at line 5748 of file sqlite3.c.
Member Data Documentation
int sqlite3_module::iVersion
Definition at line 5749 of file sqlite3.c.
Referenced by sqlite3VtabSavepoint().
int(* sqlite3_module::xBegin)(sqlite3_vtab *pVTab)
Definition at line 5768 of file sqlite3.c.
Referenced by sqlite3VtabBegin().
int(* sqlite3_module::xBestIndex)(sqlite3_vtab *pVTab, sqlite3_index_info *)
Definition at line 5756 of file sqlite3.c.
Referenced by vtabBestIndex().
int(* sqlite3_module::xClose)(sqlite3_vtab_cursor *)
Definition at line 5760 of file sqlite3.c.
Referenced by sqlite3VdbeFreeCursor().
int(* sqlite3_module::xColumn)(sqlite3_vtab_cursor *, sqlite3_context *, int)
Definition at line 5765 of file sqlite3.c.
int(* sqlite3_module::xCommit)(sqlite3_vtab *pVTab)
Definition at line 5770 of file sqlite3.c.
int(* sqlite3_module::xConnect)(sqlite3 *, void *pAux, int argc, const char *const *argv, sqlite3_vtab **ppVTab, char **)
Definition at line 5753 of file sqlite3.c.
Referenced by sqlite3VtabCallConnect().
int(* sqlite3_module::xCreate)(sqlite3 *, void *pAux, int argc, const char *const *argv, sqlite3_vtab **ppVTab, char **)
Definition at line 5750 of file sqlite3.c.
Referenced by sqlite3VtabCallCreate().
int(* sqlite3_module::xDestroy)(sqlite3_vtab *pVTab)
Definition at line 5758 of file sqlite3.c.
Referenced by sqlite3VtabCallDestroy().
int(* sqlite3_module::xDisconnect)(sqlite3_vtab *pVTab)
Definition at line 5757 of file sqlite3.c.
Referenced by sqlite3VtabUnlock().
int(* sqlite3_module::xEof)(sqlite3_vtab_cursor *)
Definition at line 5764 of file sqlite3.c.
int(* sqlite3_module::xFilter)(sqlite3_vtab_cursor *, int idxNum, const char *idxStr, int argc, sqlite3_value **argv)
Definition at line 5761 of file sqlite3.c.
int(* sqlite3_module::xFindFunction)(sqlite3_vtab *pVtab, int nArg, const char *zName, void(**pxFunc)(sqlite3_context *, int, sqlite3_value **), void **ppArg)
Definition at line 5772 of file sqlite3.c.
Referenced by sqlite3VtabOverloadFunction().
int(* sqlite3_module::xNext)(sqlite3_vtab_cursor *)
Definition at line 5763 of file sqlite3.c.
int(* sqlite3_module::xOpen)(sqlite3_vtab *pVTab, sqlite3_vtab_cursor **ppCursor)
Definition at line 5759 of file sqlite3.c.
Referenced by sqlite3VdbeExec().
int(* sqlite3_module::xRelease)(sqlite3_vtab *pVTab, int)
Definition at line 5779 of file sqlite3.c.
Referenced by sqlite3VtabSavepoint().
int(* sqlite3_module::xRename)(sqlite3_vtab *pVtab, const char *zNew)
Definition at line 5775 of file sqlite3.c.
Referenced by sqlite3AlterRenameTable().
int(* sqlite3_module::xRollback)(sqlite3_vtab *pVTab)
Definition at line 5771 of file sqlite3.c.
int(* sqlite3_module::xRollbackTo)(sqlite3_vtab *pVTab, int)
Definition at line 5780 of file sqlite3.c.
Referenced by sqlite3VtabSavepoint().
int(* sqlite3_module::xRowid)(sqlite3_vtab_cursor *, sqlite3_int64 *pRowid)
Definition at line 5766 of file sqlite3.c.
int(* sqlite3_module::xSavepoint)(sqlite3_vtab *pVTab, int)
Definition at line 5778 of file sqlite3.c.
Referenced by sqlite3VtabSavepoint().
int(* sqlite3_module::xSync)(sqlite3_vtab *pVTab)
Definition at line 5769 of file sqlite3.c.
Referenced by sqlite3VtabSync().
int(* sqlite3_module::xUpdate)(sqlite3_vtab *, int, sqlite3_value **, sqlite3_int64 *)
Definition at line 5767 of file sqlite3.c.
Referenced by sqlite3IsReadOnly().
The documentation for this struct was generated from the following files:
src/db/sqlite3/sqlite3.c
src/db/sqlite3/sqlite3.h