IRLib: xpath_string Class Reference
xpath_string Class Reference
Public Member Functions
xpath_string ()
xpath_string (const char_t *str, xpath_allocator *alloc)
xpath_string (const char_t *str, bool use_heap)
xpath_string (const char_t *begin, const char_t *end, xpath_allocator *alloc)
void append (const xpath_string &o, xpath_allocator *alloc)
const char_t * c_str () const
size_t length () const
char_t * data (xpath_allocator *alloc)
bool empty () const
bool operator== (const xpath_string &o) const
bool operator!= (const xpath_string &o) const
bool uses_heap () const
Static Private Member Functions
static char_t * duplicate_string (const char_t *string, size_t length, xpath_allocator *alloc)
static char_t * duplicate_string (const char_t *string, xpath_allocator *alloc)
Private Attributes
const char_t * _buffer
bool _uses_heap
Detailed Description
Definition at line 5863 of file pugixml.cpp.
Constructor & Destructor Documentation
xpath_string::xpath_string () [inline]
Definition at line 5885 of file pugixml.cpp.
xpath_string::xpath_string (const char_t * str, xpath_allocator * alloc) [inline, explicit]
Definition at line 5889 of file pugixml.cpp.
References _buffer, _uses_heap, and duplicate_string().
xpath_string::xpath_string (const char_t * str, bool use_heap) [inline, explicit]
Definition at line 5897 of file pugixml.cpp.
xpath_string::xpath_string (const char_t * begin, const char_t * end, xpath_allocator * alloc) [inline]
Definition at line 5901 of file pugixml.cpp.
References _buffer, _uses_heap, and duplicate_string().
Member Function Documentation
void xpath_string::append (const xpath_string & o, xpath_allocator * alloc) [inline]
Definition at line 5911 of file pugixml.cpp.
References _buffer, _uses_heap, xpath_allocator::reallocate(), and strlength().
Referenced by string_value().
const char_t* xpath_string::c_str () const [inline]
Definition at line 5945 of file pugixml.cpp.
References _buffer.
Referenced by xpath_ast_node::compare_eq(), xpath_ast_node::compare_rel(), xpath_ast_node::eval_boolean(), xpath_ast_node::eval_number(), and xpath_ast_node::eval_string().
char_t* xpath_string::data (xpath_allocator * alloc) [inline]
Definition at line 5955 of file pugixml.cpp.
References _buffer, _uses_heap, and duplicate_string().
Referenced by xpath_ast_node::eval_string().
static char_t* xpath_string::duplicate_string (const char_t * string, size_t length, xpath_allocator * alloc) [inline, static, private]
Definition at line 5868 of file pugixml.cpp.
References xpath_allocator::allocate(), and length().
Referenced by data(), duplicate_string(), and xpath_string().
static char_t* xpath_string::duplicate_string (const char_t * string, xpath_allocator * alloc) [inline, static, private]
Definition at line 5879 of file pugixml.cpp.
References duplicate_string(), and strlength().
bool xpath_string::empty () const [inline]
Definition at line 5967 of file pugixml.cpp.
References _buffer.
Referenced by xpath_ast_node::eval_boolean().
size_t xpath_string::length () const [inline]
Definition at line 5950 of file pugixml.cpp.
References _buffer, and strlength().
Referenced by duplicate_string(), xpath_ast_node::eval_number(), and xpath_ast_node::eval_string().
bool xpath_string::operator!= (const xpath_string & o) const [inline]
Definition at line 5977 of file pugixml.cpp.
References _buffer, and strequal().
bool xpath_string::operator== (const xpath_string & o) const [inline]
Definition at line 5972 of file pugixml.cpp.
References _buffer, and strequal().
bool xpath_string::uses_heap () const [inline]
Definition at line 5982 of file pugixml.cpp.
References _uses_heap.
Referenced by xpath_ast_node::eval_string().
Member Data Documentation
const char_t* xpath_string::_buffer [private]
Definition at line 5865 of file pugixml.cpp.
Referenced by append(), c_str(), data(), empty(), length(), operator!=(), operator==(), and xpath_string().
bool xpath_string::_uses_heap [private]
Definition at line 5866 of file pugixml.cpp.
Referenced by append(), data(), uses_heap(), and xpath_string().
The documentation for this class was generated from the following file:
src/parsers/xml/pugixml/src/pugixml.cpp