IRLib: src/index.cpp File Reference
src/index.cpp File Reference
#include "api/ioformat.h"
#include "backend/stemming/porter/stem.h"
#include <stdio.h>
#include <iostream>
#include <vector>
#include <cstring>
#include <stdlib.h>
#include <ctype.h>
#include <fstream>
#include <utility>
#include <boost/lexical_cast.hpp>
Defines
#define STOPWORDS_FILE "api/stopwords.txt"
#define DOCNO_MAX_DIGITS 10
#define LETTER(ch) (isupper(ch) || islower(ch))
Functions
int stemRawText (vector< string > inputFiles, string inDir)
int main (int argc, char *argv[])
Variables
map< string, string > docList
map< string, vector< pair< int,
string > > > docChar
Define Documentation
#define DOCNO_MAX_DIGITS 10
Definition at line 17 of file index.cpp.
Referenced by stemRawText().
#define LETTER (ch) (isupper(ch) || islower(ch))
Definition at line 18 of file index.cpp.
Referenced by stemRawText().
#define STOPWORDS_FILE "api/stopwords.txt"
Definition at line 16 of file index.cpp.
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 191 of file index.cpp.
References createDB(), generateStopwords(), load_input(), parse_input(), stemRawText(), STOPWORDS_FILE, and storeToDB().
int stemRawText (vector< string > inputFiles, string inDir)
Definition at line 23 of file index.cpp.
References create_stemmer(), docChar, docList, DOCNO_MAX_DIGITS, i_max, INC, stemmer::j, LETTER, s, stem(), and stopwords.
Referenced by main().
Variable Documentation
map<string, vector<pair<int, string> > > docChar
Definition at line 21 of file index.cpp.
Referenced by stemRawText().
map<string, string > docList
Definition at line 20 of file index.cpp.
Referenced by stemRawText().