IRLib: sqlite3_io_methods Struct Reference
sqlite3_io_methods Struct Reference
#include <sqlite3.h>
Public Attributes
int iVersion
int(* xClose)(sqlite3_file *)
int(* xRead)(sqlite3_file *, void *, int iAmt, sqlite3_int64 iOfst)
int(* xWrite)(sqlite3_file *, const void *, int iAmt, sqlite3_int64 iOfst)
int(* xTruncate)(sqlite3_file *, sqlite3_int64 size)
int(* xSync)(sqlite3_file *, int flags)
int(* xFileSize)(sqlite3_file *, sqlite3_int64 *pSize)
int(* xLock)(sqlite3_file *, int)
int(* xUnlock)(sqlite3_file *, int)
int(* xCheckReservedLock)(sqlite3_file *, int *pResOut)
int(* xFileControl)(sqlite3_file *, int op, void *pArg)
int(* xSectorSize)(sqlite3_file *)
int(* xDeviceCharacteristics)(sqlite3_file *)
int(* xShmMap)(sqlite3_file *, int iPg, int pgsz, int, void volatile **)
int(* xShmLock)(sqlite3_file *, int offset, int n, int flags)
void(* xShmBarrier)(sqlite3_file *)
int(* xShmUnmap)(sqlite3_file *, int deleteFlag)
int(* xFetch)(sqlite3_file *, sqlite3_int64 iOfst, int iAmt, void **pp)
int(* xUnfetch)(sqlite3_file *, sqlite3_int64 iOfst, void *p)
Detailed Description
Definition at line 1273 of file sqlite3.c.
Member Data Documentation
int sqlite3_io_methods::iVersion
Definition at line 1274 of file sqlite3.c.
Referenced by pagerFixMaplimit(), pagerReleaseMapPage(), sqlite3PagerWalSupported(), and sqlite3WalCheckpoint().
int(* sqlite3_io_methods::xCheckReservedLock)(sqlite3_file *, int *pResOut)
Definition at line 1283 of file sqlite3.c.
int(* sqlite3_io_methods::xClose)(sqlite3_file *)
Definition at line 1275 of file sqlite3.c.
Referenced by sqlite3OsClose().
int(* sqlite3_io_methods::xDeviceCharacteristics)(sqlite3_file *)
Definition at line 1286 of file sqlite3.c.
int(* sqlite3_io_methods::xFetch)(sqlite3_file *, sqlite3_int64 iOfst, int iAmt, void **pp)
Definition at line 1293 of file sqlite3.c.
int(* sqlite3_io_methods::xFileControl)(sqlite3_file *, int op, void *pArg)
Definition at line 1284 of file sqlite3.c.
int(* sqlite3_io_methods::xFileSize)(sqlite3_file *, sqlite3_int64 *pSize)
Definition at line 1280 of file sqlite3.c.
int(* sqlite3_io_methods::xLock)(sqlite3_file *, int)
Definition at line 1281 of file sqlite3.c.
int(* sqlite3_io_methods::xRead)(sqlite3_file *, void *, int iAmt, sqlite3_int64 iOfst)
Definition at line 1276 of file sqlite3.c.
int(* sqlite3_io_methods::xSectorSize)(sqlite3_file *)
Definition at line 1285 of file sqlite3.c.
Referenced by sqlite3OsSectorSize().
void(* sqlite3_io_methods::xShmBarrier)(sqlite3_file *)
Definition at line 1290 of file sqlite3.c.
int(* sqlite3_io_methods::xShmLock)(sqlite3_file *, int offset, int n, int flags)
Definition at line 1289 of file sqlite3.c.
int(* sqlite3_io_methods::xShmMap)(sqlite3_file *, int iPg, int pgsz, int, void volatile **)
Definition at line 1288 of file sqlite3.c.
Referenced by sqlite3PagerWalSupported().
int(* sqlite3_io_methods::xShmUnmap)(sqlite3_file *, int deleteFlag)
Definition at line 1291 of file sqlite3.c.
int(* sqlite3_io_methods::xSync)(sqlite3_file *, int flags)
Definition at line 1279 of file sqlite3.c.
int(* sqlite3_io_methods::xTruncate)(sqlite3_file *, sqlite3_int64 size)
Definition at line 1278 of file sqlite3.c.
int(* sqlite3_io_methods::xUnfetch)(sqlite3_file *, sqlite3_int64 iOfst, void *p)
Definition at line 1294 of file sqlite3.c.
int(* sqlite3_io_methods::xUnlock)(sqlite3_file *, int)
Definition at line 1282 of file sqlite3.c.
int(* sqlite3_io_methods::xWrite)(sqlite3_file *, const void *, int iAmt, sqlite3_int64 iOfst)
Definition at line 1277 of file sqlite3.c.
The documentation for this struct was generated from the following files:
src/db/sqlite3/sqlite3.c
src/db/sqlite3/sqlite3.h