IRLib: json Namespace Reference
json Namespace Reference
Namespaces
namespace detail
Classes
class array
class exception
class boolean_expected
class brace_expected
class bracket_expected
class colon_expected
class hex_character_expected
class quote_expected
class invalid_unicode_character
class keyword_expected
class string_expected
class value_expected
class utf16_surrogate_expected
class invalid_number
class invalid_utf8_string
class invalid_type_cast
class invalid_index
class object
struct null
class value
Typedefs
typedef boost::unordered_map
< std::string, value > map_type
typedef boost::unordered_set
< std::string > set_type
Enumerations
enum { ESCAPE_UNICODE = 0x01 }
Functions
bool is_string (const value &v)
bool is_bool (const value &v)
bool is_number (const value &v)
bool is_object (const value &v)
bool is_array (const value &v)
bool is_null (const value &v)
std::string to_string (const value &v)
bool to_bool (const value &v)
double to_number (const value &v)
object to_object (const value &v)
array to_array (const value &v)
size_t size (const value &v)
set_type keys (const value &v)
bool has_key (const value &v, const std::string &key)
size_t size (const object &o)
set_type keys (const object &o)
bool has_key (const object &o, const std::string &key)
size_t size (const array &a)
std::string pretty_print (const value &v, int options)
std::string pretty_print (const array &a, int options)
std::string pretty_print (const object &o, int options)
std::string pretty_print (const value &v)
std::string pretty_print (const array &a)
std::string pretty_print (const object &o)
template<class In >
value parse (In first, In last)
value parse (std::istream &is)
value parse (std::wistream &is)
value parse (const std::string &s)
value parse (const std::wstring &s)
std::string serialize (const value &v, int options)
std::string serialize (const array &a, int options)
std::string serialize (const object &o, int options)
std::string serialize (const value &v)
std::string serialize (const array &a)
std::string serialize (const object &o)
Typedef Documentation
typedef boost::unordered_map<std::string, value> json::map_type
Definition at line 33 of file json.h.
typedef boost::unordered_set<std::string> json::set_type
Definition at line 36 of file json.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
ESCAPE_UNICODE
Definition at line 79 of file json.h.
Function Documentation
bool json::has_key (const value & v, const std::string & key)
bool json::has_key (const object & o, const std::string & key)
bool json::is_array (const value & v) [inline]
bool json::is_bool (const value & v) [inline]
bool json::is_null (const value & v) [inline]
bool json::is_number (const value & v) [inline]
bool json::is_object (const value & v) [inline]
bool json::is_string (const value & v) [inline]
set_type json::keys (const value & v)
set_type json::keys (const object & o)
template<class In > value json::parse (In first, In last)
value json::parse (std::istream & is)
value json::parse (std::wistream & is)
value json::parse (const std::string & s)
value json::parse (const std::wstring & s)
std::string json::pretty_print (const value & v, int options)
std::string json::pretty_print (const array & a, int options)
std::string json::pretty_print (const object & o, int options)
std::string json::pretty_print (const value & v)
std::string json::pretty_print (const array & a)
std::string json::pretty_print (const object & o)
std::string json::serialize (const value & v, int options)
std::string json::serialize (const array & a, int options)
std::string json::serialize (const object & o, int options)
std::string json::serialize (const value & v)
std::string json::serialize (const array & a)
std::string json::serialize (const object & o)
size_t json::size (const value & v)
Referenced by xml_allocator::allocate_memory(), xml_allocator::allocate_memory_oob(), xpath_allocator::allocate_nothrow(), xml_allocator::allocate_page(), xml_allocator::allocate_string(), allocateSpace(), as_utf8_end(), btreeInitPage(), checkTreePage(), xml_allocator::deallocate_memory(), utf_decoder< Traits, opt_swap >::decode_latin1_block(), utf_decoder< Traits, opt_swap >::decode_utf16_block(), utf_decoder< Traits, opt_swap >::decode_utf32_block(), defragmentPage(), get_latin1_7bit_prefix_length(), sqlite3InitOne(), and sqlite3Pragma().
size_t json::size (const object & o)
size_t json::size (const array & a)
array json::to_array (const value & v)
bool json::to_bool (const value & v)
double json::to_number (const value & v)
object json::to_object (const value & v)
std::string json::to_string (const value & v)