IRLib: xpath_parser Struct Reference
xpath_parser Struct Reference
Public Member Functions
void throw_error (const char *message)
void throw_error_oom ()
void * alloc_node ()
const char_t * alloc_string (const xpath_lexer_string &value)
xpath_ast_node * parse_function_helper (ast_type_t type0, ast_type_t type1, size_t argc, xpath_ast_node *args[2])
xpath_ast_node * parse_function (const xpath_lexer_string &name, size_t argc, xpath_ast_node *args[2])
axis_t parse_axis_name (const xpath_lexer_string &name, bool &specified)
nodetest_t parse_node_test_type (const xpath_lexer_string &name)
xpath_ast_node * parse_primary_expression ()
xpath_ast_node * parse_filter_expression ()
xpath_ast_node * parse_step (xpath_ast_node *set)
xpath_ast_node * parse_relative_location_path (xpath_ast_node *set)
xpath_ast_node * parse_location_path ()
xpath_ast_node * parse_path_expression ()
xpath_ast_node * parse_union_expression ()
xpath_ast_node * parse_unary_expression ()
xpath_ast_node * parse_multiplicative_expression ()
xpath_ast_node * parse_additive_expression ()
xpath_ast_node * parse_relational_expression ()
xpath_ast_node * parse_equality_expression ()
xpath_ast_node * parse_and_expression ()
xpath_ast_node * parse_or_expression ()
xpath_ast_node * parse_expression ()
xpath_parser (const char_t *query, xpath_variable_set *variables, xpath_allocator *alloc, xpath_parse_result *result)
xpath_ast_node * parse ()
Static Public Member Functions
static xpath_ast_node * parse (const char_t *query, xpath_variable_set *variables, xpath_allocator *alloc, xpath_parse_result *result)
Public Attributes
xpath_allocator * _alloc
xpath_lexer _lexer
const char_t * _query
xpath_variable_set * _variables
xpath_parse_result * _result
Detailed Description
Definition at line 8718 of file pugixml.cpp.
Constructor & Destructor Documentation
xpath_parser::xpath_parser (const char_t * query, xpath_variable_set * variables, xpath_allocator * alloc, xpath_parse_result * result) [inline]
Definition at line 9550 of file pugixml.cpp.
Member Function Documentation
void* xpath_parser::alloc_node () [inline]
Definition at line 8753 of file pugixml.cpp.
References _alloc, xpath_allocator::allocate_nothrow(), and throw_error_oom().
Referenced by parse_additive_expression(), parse_and_expression(), parse_equality_expression(), parse_filter_expression(), parse_function(), parse_function_helper(), parse_location_path(), parse_multiplicative_expression(), parse_or_expression(), parse_path_expression(), parse_primary_expression(), parse_relational_expression(), parse_relative_location_path(), parse_step(), parse_unary_expression(), and parse_union_expression().
const char_t* xpath_parser::alloc_string (const xpath_lexer_string & value) [inline]
Definition at line 8762 of file pugixml.cpp.
References _alloc, xpath_allocator::allocate_nothrow(), xpath_lexer_string::begin, xpath_lexer_string::end, and throw_error_oom().
Referenced by parse_primary_expression(), and parse_step().
xpath_ast_node* xpath_parser::parse () [inline]
Definition at line 9554 of file pugixml.cpp.
References _lexer, xpath_lexer::current(), lex_eof, parse_expression(), and throw_error().
Referenced by parse().
static xpath_ast_node* xpath_parser::parse (const char_t * query, xpath_variable_set * variables, xpath_allocator * alloc, xpath_parse_result * result) [inline, static]
Definition at line 9567 of file pugixml.cpp.
References parse().
xpath_ast_node* xpath_parser::parse_additive_expression () [inline]
Definition at line 9447 of file pugixml.cpp.
References _lexer, alloc_node(), ast_op_add, ast_op_subtract, xpath_lexer::current(), lex_minus, lex_plus, xpath_lexer::next(), and parse_multiplicative_expression().
Referenced by parse_relational_expression().
xpath_ast_node* xpath_parser::parse_and_expression () [inline]
Definition at line 9511 of file pugixml.cpp.
References _lexer, alloc_node(), ast_op_and, xpath_lexer::contents(), xpath_lexer::current(), lex_string, xpath_lexer::next(), and parse_equality_expression().
Referenced by parse_or_expression().
axis_t xpath_parser::parse_axis_name (const xpath_lexer_string & name, bool & specified) [inline]
Definition at line 8901 of file pugixml.cpp.
References axis_ancestor, axis_ancestor_or_self, axis_attribute, axis_child, axis_descendant, axis_descendant_or_self, axis_following, axis_following_sibling, axis_namespace, axis_parent, axis_preceding, axis_preceding_sibling, axis_self, and xpath_lexer_string::begin.
Referenced by parse_step().
xpath_ast_node* xpath_parser::parse_equality_expression () [inline]
Definition at line 9492 of file pugixml.cpp.
References _lexer, alloc_node(), ast_op_equal, ast_op_not_equal, xpath_lexer::current(), lex_equal, lex_not_equal, xpath_lexer::next(), and parse_relational_expression().
Referenced by parse_and_expression().
xpath_ast_node* xpath_parser::parse_expression () [inline]
Definition at line 9545 of file pugixml.cpp.
References parse_or_expression().
Referenced by parse(), parse_filter_expression(), parse_primary_expression(), and parse_step().
xpath_ast_node* xpath_parser::parse_filter_expression () [inline]
Definition at line 9110 of file pugixml.cpp.
References _lexer, alloc_node(), ast_filter, ast_filter_posinv, xpath_lexer::current(), xpath_ast_node::is_posinv(), lex_close_square_brace, lex_open_square_brace, xpath_lexer::next(), parse_expression(), parse_primary_expression(), xpath_ast_node::rettype(), and throw_error().
Referenced by parse_path_expression().
xpath_ast_node* xpath_parser::parse_function (const xpath_lexer_string & name, size_t argc, xpath_ast_node * args[2]) [inline]
Definition at line 8788 of file pugixml.cpp.
References alloc_node(), ast_func_boolean, ast_func_ceiling, ast_func_concat, ast_func_contains, ast_func_count, ast_func_false, ast_func_floor, ast_func_id, ast_func_lang, ast_func_last, ast_func_local_name_0, ast_func_local_name_1, ast_func_name_0, ast_func_name_1, ast_func_namespace_uri_0, ast_func_namespace_uri_1, ast_func_normalize_space_0, ast_func_normalize_space_1, ast_func_not, ast_func_number_0, ast_func_number_1, ast_func_position, ast_func_round, ast_func_starts_with, ast_func_string_0, ast_func_string_1, ast_func_string_length_0, ast_func_string_length_1, ast_func_substring_2, ast_func_substring_3, ast_func_substring_after, ast_func_substring_before, ast_func_sum, ast_func_translate, ast_func_true, xpath_lexer_string::begin, parse_function_helper(), and throw_error().
Referenced by parse_primary_expression().
xpath_ast_node* xpath_parser::parse_function_helper (ast_type_t type0, ast_type_t type1, size_t argc, xpath_ast_node * args[2]) [inline]
Definition at line 8779 of file pugixml.cpp.
References alloc_node(), and throw_error().
Referenced by parse_function().
xpath_ast_node* xpath_parser::parse_location_path () [inline]
Definition at line 9304 of file pugixml.cpp.
References _lexer, alloc_node(), ast_step, ast_step_root, axis_descendant_or_self, xpath_lexer::current(), lex_axis_attribute, lex_dot, lex_double_dot, lex_double_slash, lex_multiply, lex_slash, lex_string, xpath_lexer::next(), nodetest_type_node, and parse_relative_location_path().
Referenced by parse_path_expression().
xpath_ast_node* xpath_parser::parse_multiplicative_expression () [inline]
Definition at line 9425 of file pugixml.cpp.
References _lexer, alloc_node(), ast_op_divide, ast_op_mod, ast_op_multiply, xpath_lexer_string::begin, xpath_lexer::contents(), xpath_lexer::current(), lex_multiply, lex_string, xpath_lexer::next(), and parse_unary_expression().
Referenced by parse_additive_expression().
nodetest_t xpath_parser::parse_node_test_type (const xpath_lexer_string & name) [inline]
Definition at line 8969 of file pugixml.cpp.
References xpath_lexer_string::begin, nodetest_none, nodetest_type_comment, nodetest_type_node, nodetest_type_pi, and nodetest_type_text.
Referenced by parse_path_expression(), and parse_step().
xpath_ast_node* xpath_parser::parse_or_expression () [inline]
Definition at line 9528 of file pugixml.cpp.
References _lexer, alloc_node(), ast_op_or, xpath_lexer::contents(), xpath_lexer::current(), lex_string, xpath_lexer::next(), and parse_and_expression().
Referenced by parse_expression().
xpath_ast_node* xpath_parser::parse_path_expression () [inline]
Definition at line 9338 of file pugixml.cpp.
References _lexer, alloc_node(), ast_step, axis_descendant_or_self, xpath_lexer::contents(), ct_space, xpath_lexer::current(), lex_double_slash, lex_number, lex_open_brace, lex_quoted_string, lex_slash, lex_string, lex_var_ref, xpath_lexer::next(), nodetest_none, nodetest_type_node, parse_filter_expression(), parse_location_path(), parse_node_test_type(), parse_relative_location_path(), PUGI__IS_CHARTYPE, xpath_ast_node::rettype(), xpath_lexer::state(), and throw_error().
Referenced by parse_union_expression().
xpath_ast_node* xpath_parser::parse_primary_expression () [inline]
Definition at line 9005 of file pugixml.cpp.
References _lexer, _variables, alloc_node(), alloc_string(), ast_number_constant, ast_string_constant, ast_variable, xpath_lexer_string::begin, xpath_lexer::contents(), convert_string_to_number(), xpath_lexer::current(), xpath_lexer_string::end, get_variable(), lex_close_brace, lex_comma, lex_number, lex_open_brace, lex_quoted_string, lex_string, lex_var_ref, xpath_lexer::next(), parse_expression(), parse_function(), xpath_ast_node::set_next(), throw_error(), and throw_error_oom().
Referenced by parse_filter_expression().
xpath_ast_node* xpath_parser::parse_relational_expression () [inline]
Definition at line 9470 of file pugixml.cpp.
References _lexer, alloc_node(), ast_op_greater, ast_op_greater_or_equal, ast_op_less, ast_op_less_or_equal, xpath_lexer::current(), lex_greater, lex_greater_or_equal, lex_less, lex_less_or_equal, xpath_lexer::next(), and parse_additive_expression().
Referenced by parse_equality_expression().
xpath_ast_node* xpath_parser::parse_relative_location_path (xpath_ast_node * set) [inline]
Definition at line 9284 of file pugixml.cpp.
References _lexer, alloc_node(), ast_step, axis_descendant_or_self, xpath_lexer::current(), lex_double_slash, lex_slash, xpath_lexer::next(), nodetest_type_node, and parse_step().
Referenced by parse_location_path(), and parse_path_expression().
xpath_ast_node* xpath_parser::parse_step (xpath_ast_node * set) [inline]
Definition at line 9140 of file pugixml.cpp.
References _lexer, alloc_node(), alloc_string(), ast_predicate, ast_step, axis_attribute, axis_child, axis_parent, axis_self, xpath_lexer_string::begin, xpath_lexer::contents(), xpath_lexer::current(), xpath_lexer_string::end, lex_axis_attribute, lex_close_brace, lex_close_square_brace, lex_dot, lex_double_colon, lex_double_dot, lex_multiply, lex_open_brace, lex_open_square_brace, lex_quoted_string, lex_string, xpath_lexer::next(), nodetest_all, nodetest_all_in_namespace, nodetest_name, nodetest_none, nodetest_pi, nodetest_type_node, parse_axis_name(), parse_expression(), parse_node_test_type(), xpath_ast_node::set_next(), xpath_ast_node::set_right(), and throw_error().
Referenced by parse_relative_location_path().
xpath_ast_node* xpath_parser::parse_unary_expression () [inline]
Definition at line 9408 of file pugixml.cpp.
References _lexer, alloc_node(), ast_op_negate, xpath_lexer::current(), lex_minus, xpath_lexer::next(), and parse_union_expression().
Referenced by parse_multiplicative_expression().
xpath_ast_node* xpath_parser::parse_union_expression () [inline]
Definition at line 9388 of file pugixml.cpp.
References _lexer, alloc_node(), ast_op_union, xpath_lexer::current(), lex_union, xpath_lexer::next(), parse_path_expression(), xpath_ast_node::rettype(), and throw_error().
Referenced by parse_unary_expression().
void xpath_parser::throw_error (const char * message) [inline]
Definition at line 8732 of file pugixml.cpp.
References _lexer, _query, _result, and xpath_lexer::current_pos().
Referenced by parse(), parse_filter_expression(), parse_function(), parse_function_helper(), parse_path_expression(), parse_primary_expression(), parse_step(), parse_union_expression(), and throw_error_oom().
void xpath_parser::throw_error_oom () [inline]
Definition at line 8744 of file pugixml.cpp.
References throw_error().
Referenced by alloc_node(), alloc_string(), and parse_primary_expression().
Member Data Documentation
xpath_allocator* xpath_parser::_alloc
Definition at line 8720 of file pugixml.cpp.
Referenced by alloc_node(), and alloc_string().
xpath_lexer xpath_parser::_lexer
Definition at line 8721 of file pugixml.cpp.
Referenced by parse(), parse_additive_expression(), parse_and_expression(), parse_equality_expression(), parse_filter_expression(), parse_location_path(), parse_multiplicative_expression(), parse_or_expression(), parse_path_expression(), parse_primary_expression(), parse_relational_expression(), parse_relative_location_path(), parse_step(), parse_unary_expression(), parse_union_expression(), and throw_error().
const char_t* xpath_parser::_query
Definition at line 8723 of file pugixml.cpp.
Referenced by throw_error().
xpath_parse_result* xpath_parser::_result
Definition at line 8726 of file pugixml.cpp.
Referenced by throw_error().
xpath_variable_set* xpath_parser::_variables
Definition at line 8724 of file pugixml.cpp.
Referenced by parse_primary_expression().
The documentation for this struct was generated from the following file:
src/parsers/xml/pugixml/src/pugixml.cpp