IRLib: xpath_lexer Class Reference
xpath_lexer Class Reference
Public Member Functions
xpath_lexer (const char_t *query)
const char_t * state () const
void next ()
lexeme_t current () const
const char_t * current_pos () const
const xpath_lexer_string & contents () const
Private Attributes
const char_t * _cur
const char_t * _cur_lexeme_pos
xpath_lexer_string _cur_lexeme_contents
lexeme_t _cur_lexeme
Detailed Description
Definition at line 6973 of file pugixml.cpp.
Constructor & Destructor Documentation
xpath_lexer::xpath_lexer (const char_t * query) [inline, explicit]
Definition at line 6982 of file pugixml.cpp.
References next().
Member Function Documentation
const xpath_lexer_string& xpath_lexer::contents () const [inline]
Definition at line 7271 of file pugixml.cpp.
References _cur_lexeme, _cur_lexeme_contents, lex_number, lex_quoted_string, lex_string, and lex_var_ref.
Referenced by xpath_parser::parse_and_expression(), xpath_parser::parse_multiplicative_expression(), xpath_parser::parse_or_expression(), xpath_parser::parse_path_expression(), xpath_parser::parse_primary_expression(), and xpath_parser::parse_step().
lexeme_t xpath_lexer::current () const [inline]
Definition at line 7261 of file pugixml.cpp.
References _cur_lexeme.
Referenced by xpath_parser::parse(), xpath_parser::parse_additive_expression(), xpath_parser::parse_and_expression(), xpath_parser::parse_equality_expression(), xpath_parser::parse_filter_expression(), xpath_parser::parse_location_path(), xpath_parser::parse_multiplicative_expression(), xpath_parser::parse_or_expression(), xpath_parser::parse_path_expression(), xpath_parser::parse_primary_expression(), xpath_parser::parse_relational_expression(), xpath_parser::parse_relative_location_path(), xpath_parser::parse_step(), xpath_parser::parse_unary_expression(), and xpath_parser::parse_union_expression().
const char_t* xpath_lexer::current_pos () const [inline]
Definition at line 7266 of file pugixml.cpp.
References _cur_lexeme_pos.
Referenced by xpath_parser::throw_error().
void xpath_lexer::next () [inline]
Definition at line 6992 of file pugixml.cpp.
References _cur, _cur_lexeme, _cur_lexeme_contents, _cur_lexeme_pos, xpath_lexer_string::begin, ct_space, ctx_digit, ctx_start_symbol, ctx_symbol, xpath_lexer_string::end, lex_axis_attribute, lex_close_brace, lex_close_square_brace, lex_comma, lex_dot, lex_double_colon, lex_double_dot, lex_double_slash, lex_eof, lex_equal, lex_greater, lex_greater_or_equal, lex_less, lex_less_or_equal, lex_minus, lex_multiply, lex_none, lex_not_equal, lex_number, lex_open_brace, lex_open_square_brace, lex_plus, lex_quoted_string, lex_slash, lex_string, lex_union, lex_var_ref, PUGI__IS_CHARTYPE, and PUGI__IS_CHARTYPEX.
Referenced by xpath_parser::parse_additive_expression(), xpath_parser::parse_and_expression(), xpath_parser::parse_equality_expression(), xpath_parser::parse_filter_expression(), xpath_parser::parse_location_path(), xpath_parser::parse_multiplicative_expression(), xpath_parser::parse_or_expression(), xpath_parser::parse_path_expression(), xpath_parser::parse_primary_expression(), xpath_parser::parse_relational_expression(), xpath_parser::parse_relative_location_path(), xpath_parser::parse_step(), xpath_parser::parse_unary_expression(), xpath_parser::parse_union_expression(), and xpath_lexer().
const char_t* xpath_lexer::state () const [inline]
Definition at line 6987 of file pugixml.cpp.
References _cur.
Referenced by xpath_parser::parse_path_expression().
Member Data Documentation
const char_t* xpath_lexer::_cur [private]
Definition at line 6975 of file pugixml.cpp.
Referenced by next(), and state().
lexeme_t xpath_lexer::_cur_lexeme [private]
Definition at line 6979 of file pugixml.cpp.
Referenced by contents(), current(), and next().
xpath_lexer_string xpath_lexer::_cur_lexeme_contents [private]
Definition at line 6977 of file pugixml.cpp.
Referenced by contents(), and next().
const char_t* xpath_lexer::_cur_lexeme_pos [private]
Definition at line 6976 of file pugixml.cpp.
Referenced by current_pos(), and next().
The documentation for this class was generated from the following file:
src/parsers/xml/pugixml/src/pugixml.cpp