IRLib: xml_parser Struct Reference
xml_parser Struct Reference
Public Member Functions
xml_parser (const xml_allocator &alloc_)
char_t * parse_doctype_primitive (char_t *s)
char_t * parse_doctype_ignore (char_t *s)
char_t * parse_doctype_group (char_t *s, char_t endch, bool toplevel)
char_t * parse_exclamation (char_t *s, xml_node_struct *cursor, unsigned int optmsk, char_t endch)
char_t * parse_question (char_t *s, xml_node_struct *&ref_cursor, unsigned int optmsk, char_t endch)
char_t * parse (char_t *s, xml_node_struct *xmldoc, unsigned int optmsk, char_t endch)
Static Public Member Functions
static xml_parse_result parse (char_t *buffer, size_t length, xml_node_struct *root, unsigned int optmsk)
Public Attributes
xml_allocator alloc
char_t * error_offset
xml_parse_status error_status
Detailed Description
Definition at line 2050 of file pugixml.cpp.
Constructor & Destructor Documentation
xml_parser::xml_parser (const xml_allocator & alloc_) [inline]
Definition at line 2067 of file pugixml.cpp.
Member Function Documentation
char_t* xml_parser::parse (char_t * s, xml_node_struct * xmldoc, unsigned int optmsk, char_t endch) [inline]
Definition at line 2383 of file pugixml.cpp.
References alloc, append_attribute_ll(), ct_space, ct_start_symbol, ct_symbol, ENDSWITH, get_strconv_attribute(), get_strconv_pcdata(), parse_exclamation(), parse_question(), PUGI__CHECK_ERROR, PUGI__ENDSEG, PUGI__IS_CHARTYPE, PUGI__OPTSET, PUGI__POPNODE, PUGI__PUSHNODE, PUGI__SCANFOR, PUGI__SCANWHILE, PUGI__SKIPWS, PUGI__THROW_ERROR, and s.
Referenced by parse().
static xml_parse_result xml_parser::parse (char_t * buffer, size_t length, xml_node_struct * root, unsigned int optmsk) [inline, static]
Definition at line 2614 of file pugixml.cpp.
References alloc, xml_document_struct::buffer, error_offset, error_status, make_parse_result(), and parse().
char_t* xml_parser::parse_doctype_group (char_t * s, char_t endch, bool toplevel) [inline]
Definition at line 2137 of file pugixml.cpp.
References parse_doctype_ignore(), parse_doctype_primitive(), PUGI__THROW_ERROR, and s.
Referenced by parse_exclamation().
char_t* xml_parser::parse_doctype_ignore (char_t * s) [inline]
Definition at line 2111 of file pugixml.cpp.
References PUGI__THROW_ERROR, and s.
Referenced by parse_doctype_group().
char_t* xml_parser::parse_doctype_primitive (char_t * s) [inline]
Definition at line 2078 of file pugixml.cpp.
References PUGI__SCANFOR, PUGI__THROW_ERROR, and s.
Referenced by parse_doctype_group().
char_t* xml_parser::parse_exclamation (char_t * s, xml_node_struct * cursor, unsigned int optmsk, char_t endch) [inline]
Definition at line 2179 of file pugixml.cpp.
References ct_space, ENDSWITH, parse_doctype_group(), PUGI__CHECK_ERROR, PUGI__IS_CHARTYPE, PUGI__OPTSET, PUGI__POPNODE, PUGI__PUSHNODE, PUGI__SCANFOR, PUGI__THROW_ERROR, s, strconv_cdata(), and strconv_comment().
Referenced by parse().
char_t* xml_parser::parse_question (char_t * s, xml_node_struct *& ref_cursor, unsigned int optmsk, char_t endch) [inline]
Definition at line 2290 of file pugixml.cpp.
References ct_space, ct_start_symbol, ct_symbol, ENDSWITH, PUGI__CHECK_ERROR, PUGI__ENDSEG, PUGI__IS_CHARTYPE, PUGI__OPTSET, PUGI__POPNODE, PUGI__PUSHNODE, PUGI__SCANFOR, PUGI__SCANWHILE, PUGI__SKIPWS, PUGI__THROW_ERROR, and s.
Referenced by parse().
Member Data Documentation
xml_allocator xml_parser::alloc
Definition at line 2052 of file pugixml.cpp.
Referenced by parse().
char_t* xml_parser::error_offset
Definition at line 2053 of file pugixml.cpp.
Referenced by parse().
xml_parse_status xml_parser::error_status
Definition at line 2054 of file pugixml.cpp.
Referenced by parse().
The documentation for this struct was generated from the following file:
src/parsers/xml/pugixml/src/pugixml.cpp