IRLib: src/backend/stemming/porter/stem.h File Reference
src/backend/stemming/porter/stem.h File Reference
Functions
struct stemmer * create_stemmer (void)
void free_stemmer (struct stemmer *z)
int stem (struct stemmer *z, char *b, int k)
Function Documentation
struct stemmer* create_stemmer (void) [read]
Definition at line 75 of file stem.c.
Referenced by stemRawText().
void free_stemmer (struct stemmer * z)
Definition at line 81 of file stem.c.
int stem (struct stemmer * z, char * b, int k)
Definition at line 363 of file stem.c.
References stemmer::b, stemmer::k, step1ab(), step1c(), step2(), step3(), step4(), and step5().
Referenced by stemfile(), and stemRawText().