IRLib: src/api/ioformat.cpp File Reference
src/api/ioformat.cpp File Reference
#include "../parsers/xml/pugixml/src/pugixml.hpp"
#include "../parsers/json/cpp-json/json.h"
#include "../db/sqlite3/sqlite3.h"
#include "ioformat.h"
#include <iostream>
#include <cstring>
#include <vector>
#include <dirent.h>
#include <stdlib.h>
#include <algorithm>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <boost/lexical_cast.hpp>
Defines
#define DB_NAME "../indexes/db_index.sqlite"
#define BUFFER_SIZE 256
Functions
vector< string > load_input (const char *p_input)
Takes a directory as input Returns all the files present in the directory.
static int callback (void *NotUsed, int argc, char **argv, char **azColName)
Callback for sqlite3 queries.
void generateStopwords (const char *stopwordFile)
int createDB ()
int storeToDB ()
int parse_input (vector< string > inputFiles, string inDir)
Takes files as input Parses the XML documents Creates a map of the features that need to be indexed.
Variables
map< string, int > stopwords
Define Documentation
#define BUFFER_SIZE 256
Definition at line 127 of file ioformat.cpp.
#define DB_NAME "../indexes/db_index.sqlite"
Definition at line 21 of file ioformat.cpp.
Referenced by createDB().
Function Documentation
static int callback (void * NotUsed, int argc, char ** argv, char ** azColName) [static]
Callback for sqlite3 queries.
Definition at line 49 of file ioformat.cpp.
Referenced by createDB().
int createDB ()
Definition at line 100 of file ioformat.cpp.
References callback(), db, DB_NAME, sqlite3_close, sqlite3_errmsg, sqlite3_exec, sqlite3_free, sqlite3_open, and SQLITE_OK.
Referenced by main().
void generateStopwords (const char * stopwordFile)
Definition at line 59 of file ioformat.cpp.
References stopwords.
Referenced by main().
vector<string> load_input (const char * p_input)
Takes a directory as input Returns all the files present in the directory.
Definition at line 30 of file ioformat.cpp.
Referenced by main().
int parse_input (vector< string > inputFiles, string inDir)
Takes files as input Parses the XML documents Creates a map of the features that need to be indexed.
Definition at line 171 of file ioformat.cpp.
Referenced by main().
int storeToDB ()
Definition at line 130 of file ioformat.cpp.
Referenced by main().
Variable Documentation
map<string, int> stopwords
Definition at line 23 of file ioformat.cpp.
Referenced by generateStopwords(), and stemRawText().